# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('caesarapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
