# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caesarapp', '0002_userinput_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinput',
            old_name='key',
            new_name='encryption_key',
        ),
    ]
